---
- name: Setup Git with SSH and add key to GitHub
  hosts: localhost
  become: true
  vars:
    git_user_name: "TheBranchDriftCatalyst"
    git_user_email: "djdanielsh@gmail.com"
    ssh_key_comment: "djdanielsh@gmail.com"
    ssh_key_path: "~/.ssh/id_rsa"
    # https://github.com/settings/tokens?type=beta
    # make sure it has readwrite access to sshe keys
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
  tasks:
    # - name: Update apt repository cache
    #   apt:
    #     update_cache: yes

    # - name: Install Git
    #   apt:
    #     name: git
    #     state: present

    # - name: Install OpenSSH client
    #   apt:
    #     name: openssh-client
    #     state: present

    - name: Check if SSH key already exists
      stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key

    - name: Generate a new SSH key pair
      command: ssh-keygen -t rsa -b 2048 -C "{{ ssh_key_comment }}" -f {{ ssh_key_path }} -N ""
      when: not ssh_key.stat.exists

    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'
        owner: panda

    - name: Copy public key to remote authorized_keys
      authorized_key:
        user: panda
        state: present
        key: "{{ lookup('file', ssh_key_path + '.pub') }}"

    - name: Ensure global Git configuration file exists
      file:
        path: "{{ ansible_env.HOME }}/.gitconfig"
        state: touch

    - name: Configure Git user name
      command: git config user.name "{{ git_user_name }}"

    - name: Configure Git user email
      command: git config user.email "{{ git_user_email }}"

    - name: Add GitHub to known hosts (example for GitHub)
      known_hosts:
        path: ~/.ssh/known_hosts
        name: github.com
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"

    - name: Read the SSH public key
      slurp:
        src: "{{ ssh_key_path }}.pub"
      register: ssh_pub_key
    
    - name: Add SSH key to GitHub
      uri:
        url: https://api.github.com/user/keys
        method: POST
        headers:
          Accept: "application/vnd.github+json"
          Authorization: "Bearer {{ github_token }}"
          "X-GitHub-Api-Version": "2022-11-28"
        body: "{{ {'title': ansible_host, 'key': ssh_pub_key.content | b64decode} | to_json }}"
        status_code: 201
      when: ssh_key.stat.exists
